-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 04:46:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
                                                     `id_departamento` INT NOT NULL AUTO_INCREMENT,
                                                     `descricao` VARCHAR(45) NULL,
    PRIMARY KEY (`id_departamento`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
    `usuario` VARCHAR(16) NOT NULL,
    `senha` VARCHAR(32) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `nome` VARCHAR(255) NOT NULL,
    `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `data_alteracao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `ativo` TINYINT NULL DEFAULT 1,
    `id_departamento` INT NULL DEFAULT 1,
    UNIQUE INDEX `username_UNIQUE` (`usuario` ASC) VISIBLE,
    PRIMARY KEY (`usuario`),
    INDEX `fk_usuario_departamento1_idx` (`id_departamento` ASC) VISIBLE,
    CONSTRAINT `fk_usuario_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
                                                `codigo` INT NOT NULL,
                                                `razao` VARCHAR(45) NULL,
    PRIMARY KEY (`codigo`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gerente_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gerente_funcionario` (
                                                            `id_relacao` INT NOT NULL AUTO_INCREMENT,
                                                            `gerente` VARCHAR(16) NULL,
    `funcionario` VARCHAR(16) NULL,
    INDEX `fk_funcionario_usuario_idx` (`funcionario` ASC) VISIBLE,
    INDEX `fk_gerente_usuario_idx` (`gerente` ASC) VISIBLE,
    PRIMARY KEY (`id_relacao`),
    CONSTRAINT `fk_funcionario_usuario`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_gerente_usuario`
    FOREIGN KEY (`gerente`)
    REFERENCES `mydb`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aux_empresa_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aux_empresa_usuario` (
                                                            `id_relacao` INT NOT NULL AUTO_INCREMENT,
                                                            `cod_empresa` INT NOT NULL,
                                                            `usuario` VARCHAR(16) NOT NULL,
    `padrao` TINYINT NULL DEFAULT 0,
    PRIMARY KEY (`id_relacao`),
    INDEX `fk_aux_empresa_usuario_empresa1_idx` (`cod_empresa` ASC) VISIBLE,
    INDEX `fk_aux_empresa_usuario_usuario1_idx` (`usuario` ASC) VISIBLE,
    CONSTRAINT `fk_aux_empresa_usuario_empresa1`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `mydb`.`empresa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_aux_empresa_usuario_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aux_departamento_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aux_departamento_empresa` (
                                                                 `id_relacao` INT NOT NULL AUTO_INCREMENT,
                                                                 `id_departamento` INT NOT NULL,
                                                                 `empresa` INT NOT NULL,
                                                                 INDEX `fk_aux_departamento_empresa_departamento1_idx` (`id_departamento` ASC) VISIBLE,
    INDEX `fk_aux_departamento_empresa_empresa1_idx` (`empresa` ASC) VISIBLE,
    PRIMARY KEY (`id_relacao`),
    CONSTRAINT `fk_aux_departamento_empresa_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_aux_departamento_empresa_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `mydb`.`empresa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kpi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kpi` (
                                            `id_kpi` INT NOT NULL AUTO_INCREMENT,
                                            `descricao` VARCHAR(255) NULL,
    `tipo` VARCHAR(45) NOT NULL,
    `aux_departamento_empresa_id_relacao` INT NOT NULL,
    PRIMARY KEY (`id_kpi`),
    INDEX `fk_kpi_aux_departamento_empresa1_idx` (`aux_departamento_empresa_id_relacao` ASC) VISIBLE,
    CONSTRAINT `fk_kpi_aux_departamento_empresa1`
    FOREIGN KEY (`aux_departamento_empresa_id_relacao`)
    REFERENCES `mydb`.`aux_departamento_empresa` (`id_relacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/* Refactor:
create table if not exists aux_emp_usuario
(
    usuario varchar(20) not null,
    empresa int         not null,
    padrao  varchar(1)  not null,
    primary key (usuario, empresa)
    );

create table if not exists aux_perfil_usuario
(
    perfil  int         not null,
    usuario varchar(20) not null,
    primary key (perfil, usuario)
    );

create table if not exists empresa
(
    codigo int         not null
    primary key,
    nome   varchar(50) not null
    );

create table if not exists perfil
(
    id_perfil int         not null
    primary key,
    descricao varchar(50) not null
    );

create table if not exists setor
(
    id_setor  int auto_increment
    primary key,
    descricao varchar(50) not null
    );

create table if not exists usuario
(
    usuario  varchar(20)            not null
    primary key,
    senha    varchar(50)            not null,
    nome     varchar(50)            not null,
    id_setor int        default 1   not null,
    ativo    varchar(1) default 'A' not null
    );
*/
